// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model_UN_Crisis.DAL;

#nullable disable

namespace Model_UN_Crisis.Migrations
{
    [DbContext(typeof(ModelUNDbContext))]
    [Migration("20240410215623_master")]
    partial class master
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Conferences", b =>
                {
                    b.Property<int>("Iconference_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iconference_Id"));

                    b.Property<int>("Iprimary_Admin")
                        .HasColumnType("int");

                    b.HasKey("Iconference_Id");

                    b.ToTable("PRD_Conferences");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Directives", b =>
                {
                    b.Property<int>("Idirective_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idirective_Id"));

                    b.Property<byte[]>("Bimage")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Cstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iassigned_Staff")
                        .HasColumnType("int");

                    b.Property<int>("Iauthor")
                        .HasColumnType("int");

                    b.Property<int>("Ico_Author_1")
                        .HasColumnType("int");

                    b.Property<int>("Ico_Author_2")
                        .HasColumnType("int");

                    b.HasKey("Idirective_Id");

                    b.ToTable("PRD_Directives");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Files", b =>
                {
                    b.Property<int>("Ifile_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ifile_Id"));

                    b.Property<byte[]>("Bfile")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("Iconference_Id")
                        .HasColumnType("int");

                    b.HasKey("Ifile_Id");

                    b.ToTable("PRD_Files");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Message_Groups", b =>
                {
                    b.Property<int>("Igroup_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Igroup_Id"));

                    b.Property<int>("Iuser_Id")
                        .HasColumnType("int");

                    b.HasKey("Igroup_Id");

                    b.ToTable("PRD_Message_Groups");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Messages", b =>
                {
                    b.Property<int>("Imessage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Imessage_Id"));

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iauthor")
                        .HasColumnType("int");

                    b.Property<int>("Igroup_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ttimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Imessage_Id");

                    b.ToTable("PRD_Messages");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_News", b =>
                {
                    b.Property<int>("Inews_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inews_Id"));

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iconference_Id")
                        .HasColumnType("int");

                    b.HasKey("Inews_Id");

                    b.ToTable("PRD_News");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.PRD_Users", b =>
                {
                    b.Property<int>("Iuser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iuser_id"));

                    b.Property<string>("CaccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cusername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iuser_id");

                    b.ToTable("PRD_Users");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Conferences", b =>
                {
                    b.Property<int>("Iconference_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iconference_Id"));

                    b.Property<int>("Iprimary_Admin")
                        .HasColumnType("int");

                    b.HasKey("Iconference_Id");

                    b.ToTable("STG_Conferences");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Directives", b =>
                {
                    b.Property<int>("Idirective_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idirective_Id"));

                    b.Property<byte[]>("Bimage")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Cstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iassigned_Staff")
                        .HasColumnType("int");

                    b.Property<int>("Iauthor")
                        .HasColumnType("int");

                    b.Property<int>("Ico_Author_1")
                        .HasColumnType("int");

                    b.Property<int>("Ico_Author_2")
                        .HasColumnType("int");

                    b.HasKey("Idirective_Id");

                    b.ToTable("STG_Directives");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Files", b =>
                {
                    b.Property<int>("Ifile_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ifile_Id"));

                    b.Property<byte[]>("Bfile")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("Iconference_Id")
                        .HasColumnType("int");

                    b.HasKey("Ifile_Id");

                    b.ToTable("STG_Files");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Message_Groups", b =>
                {
                    b.Property<int>("Igroup_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Igroup_Id"));

                    b.Property<int>("Iuser_Id")
                        .HasColumnType("int");

                    b.HasKey("Igroup_Id");

                    b.ToTable("STG_Message_Groups");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Messages", b =>
                {
                    b.Property<int>("Imessage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Imessage_Id"));

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iauthor")
                        .HasColumnType("int");

                    b.Property<int>("Igroup_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ttimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Imessage_Id");

                    b.ToTable("STG_Messages");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_News", b =>
                {
                    b.Property<int>("Inews_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inews_Id"));

                    b.Property<string>("Ctext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Iconference_Id")
                        .HasColumnType("int");

                    b.HasKey("Inews_Id");

                    b.ToTable("STG_News");
                });

            modelBuilder.Entity("Model_UN_Crisis.Models.STG_Users", b =>
                {
                    b.Property<int>("Iuser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iuser_id"));

                    b.Property<string>("CaccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cusername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iuser_id");

                    b.ToTable("STG_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
